name: Build, Push and Deploy to Azure App Service

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY_NAME: "puissance4containerregistry"
  IMAGE_NAME: "puissance4image"
  AZURE_WEBAPP_NAME: "puissance4-client-app"
  # J'ai enlevé les variables non utilisées pour plus de clarté

jobs:
  build:
    runs-on: ubuntu-latest
    # On définit une "sortie" pour que le job 'deploy' sache quel tag d'image utiliser
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE }}

      - name: Docker Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}
          tags: type=sha,format=short # Crée un tag comme "sha-a1b2c3d"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Utilise le tag de l'étape "meta"
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE }}
          enable-AzPSSession: true 
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ needs.build.outputs.image_tag }}