name: Build, Push and Deploy to Azure App Service

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY_NAME: "puissance4containerregistry"
  IMAGE_NAME: "puissance4image"
  ANGULAR_APP_NAME: "puissance4Angular"
  AZURE_RESOURCE_GROUP: "testdevops"
  AZURE_WEBAPP_NAME: "puissance4-client-app"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}
          tags: type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ANGULAR_APP_NAME=${{ env.ANGULAR_APP_NAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE }}
          
      - name: Docker Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        # Cette action utilise les identifiants de l'étape "Azure Login" précédente

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Chemin vers votre Dockerfile
          push: true
          tags: ${{ env.REGISTRY_NAME }}.azurecr.io/samples/${{ env.IMAGE_NAME }}:latest
